### PR TITLE
reinstate Measurements tests

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Peculiar

**Comment by giordano** [comment]
Segmentation fault https://gitlab.com/PumasAI/Pumas-jl/-/jobs/265588871? :thinking:

**Comment by ChrisRackauckas** [comment]
🤷‍♂ . Also,

```
┌ Warning: Package Measurements does not have SpecialFunctions in its dependencies:
│ - If you have Measurements checked out for development and have
│   added SpecialFunctions as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Measurements
└ Loading SpecialFunctions into Measurements from project dependency, future warnings for Measurements are suppressed.
```

**Comment by giordano** [comment]
Already fixed: https://github.com/JuliaPhysics/Measurements.jl/issues/49  And new release waiting at: https://github.com/JuliaRegistries/General/pull/2506

**Comment by andreasnoack** [comment]
It looks like they still trigger a segfault.

**Comment by ChrisRackauckas** [comment]
Yeah, it fooled me because it is nondeterministic...

**Pull request merged**
