### PR TITLE
WIP: Implement series recipes for interpolations

### PR DESCRIPTION
**Pull request by asinghvi17**
Uses the DataInterpolations.jl library to generate these.  Still untested.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should these go into DataInterpolations.jl?

**Comment by asinghvi17** [comment]
Possibly, if you want to take a dep on RecipesBase there.  The entire file could actually go there with no issues, we may also want to consider upstreaming to Plots.jl

**Comment by ChrisRackauckas** [comment]
A RecipesBase dep is fine there.

**Comment by asinghvi17** [comment]
Will move these there!

**Comment by asinghvi17** [comment]
I have a working branch with these, but don't have push access to the repo.  Closing in favour of said future PR.

**Pull request closed without merging**
