### PR TITLE
lower default tolerance for estimation and use a different solver

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/PumasAI/Pumas.jl/issues/602 . By using a lower tolerance, the line search tends to succeed. However, with these tolerances it enters a different performance regime. In this regime, Rodas5 is stable enough and will be faster than Rosenbrock23, while Vern9 is probably the fastest non-stiff method but has higher compile times, so Vern7 is a good middle ground. 

@vjd can you test these new defaults on some examples that were failing?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
From Vijay's tests we know this is at least better, and from the discussions we know this is theoretically better, so I am going to merge as it's a clear improvement. We can continue testing to see if it fixes all of the issues, but even then having this done should isolate any remaining inference issues to something else.

**Comment by pkofod** [comment]
Yup, looks good to me as well. We might want to look at some different methods and see how AD'ing through them works as there might be a compile time trade off (I think the new version was slightly slower than the previous default?), but again, robustness wins over compile time unless it's extreme imo.

**Comment by ChrisRackauckas** [comment]
>I think the new version was slightly slower than the previous default?

Yeah slightly, we are `@..`'ing some larger expressions so the code generation is a bit more.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/verner_rk_perform_step.jl#L246

The fastest method in this case is most definitely Vern9, but 

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/verner_rk_perform_step.jl#L563

the compiler really doesn't like this line. We can see whether it's acceptable though, it's just a small swap to `AutoVern9` instead. For long optimizations it's 100% what you'd want to run.

**Comment by ChrisRackauckas** [comment]
If someone really wants to go deep, you can test https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/904 and see if that improves timing at all in this case.

**Pull request merged**
