### PR TITLE
Bump DiffEqDiffTools version

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
OrdinaryDiffEq 5.20.0 can make use of some performance enhancements of DiffEqDiffTools in the main Pumas case, so let's see what CI digs up if we bump this.

### CODE REVIEW

**Comment by andreasnoack** [comment]
See https://gitlab.com/PumasAI/Pumas-jl/pipelines/95295045

**Comment by ChrisRackauckas** [comment]
Yes exactly, that's the old results. The core issue should be fixed though.

**Comment by andreasnoack** [comment]
> The core issue should be fixed though.

Which fix are you referring to here? It looks like the tests failures here are the same as before.

**Comment by ChrisRackauckas** [comment]
>It looks like the tests failures here are the same as before.

No they are not.

**Comment by andreasnoack** [comment]
https://gitlab.com/PumasAI/Pumas-jl/-/jobs/349352534#L323 and https://gitlab.com/PumasAI/Pumas-jl/-/jobs/348056149#L324 are exactly the same errors.

**Comment by ChrisRackauckas** [comment]
Yes they are. Good thing that's fixed! The latest result is: https://gitlab.com/PumasAI/Pumas-jl/-/jobs/349385839

**Comment by ChrisRackauckas** [comment]
Hotfix: https://github.com/JuliaDiffEq/SparseDiffTools.jl/commit/25ca2e0a070ff7fcf7942517e41e10e23191f25f

**Comment by ChrisRackauckas** [comment]
There is an autodiff issue to open now:

```julia
using Pumas

theopmodel_solver_fo = @model begin
  @param begin
    θ₁ ∈ RealDomain(lower=0.1,    upper=5.0, init=2.77)
    θ₂ ∈ RealDomain(lower=0.0008, upper=0.5, init=0.0781)
    θ₃ ∈ RealDomain(lower=0.004,  upper=0.9, init=0.0363)
    θ₄ ∈ RealDomain(lower=0.1,    upper=5.0, init=1.5)
    Ω ∈ PSDDomain(3)
    σ_add ∈ RealDomain(lower=0.001, init=0.388)
    #σ_prop ∈ RealDomain(init=0.3)
  end

  @random begin
    η ~ MvNormal(Ω)
  end

  @pre begin
    Ka = SEX == 0 ? θ₁ + η[1] : θ₄ + η[1]
    K  = θ₂+ η[2]
    CL = θ₃*WT + η[3]
    V  = CL/K
    SC = CL/K/WT
  end

  @covariates SEX WT

  @vars begin
    conc = Central / SC
    cp   = Central/V
  end

  @dynamics begin
      Depot'   = -Ka*Depot
      Central' =  Ka*Depot - (CL/V)*Central
  end

  @derived begin
    dv ~ @. Normal(conc,sqrt(σ_add))
  end
end

theopp = read_pumas(example_data("event_data/THEOPP"),cvs = [:SEX,:WT])

param = (
  θ₁ = 2.77,   #Ka MEAN ABSORPTION RATE CONSTANT for SEX = 1(1/HR)
  θ₂ = 0.0781, #K MEAN ELIMINATION RATE CONSTANT (1/HR)
  θ₃ = 0.0363, #SLP  SLOPE OF CLEARANCE VS WEIGHT RELATIONSHIP (LITERS/HR/KG)
  θ₄ = 1.5,    #Ka MEAN ABSORPTION RATE CONSTANT for SEX=0 (1/HR)
  Ω  = diagm(0 => [5.55, 0.0024, 0.515]), # update to block diagonal
  σ_add = 0.388
  # σ_prop = 0.3
     )

o = fit(theopmodel_solver_fo, theopp, param, Pumas.FO(), alg=Rosenbrock23())
```

but honestly it's probably better to not nest that into the ODE solver, so the default algorithm was changed and everything works fine. But I'll open an issue to track this MWE.

**Pull request merged**
