### PR TITLE
Event-based DCP Overhaul

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Makes the DCP calculations directly based on events at their times. Fixes https://github.com/PumasAI/Pumas.jl/issues/538 , Fixes https://github.com/PumasAI/Pumas.jl/issues/787 . Fixes https://github.com/PumasAI/Pumas.jl/issues/649 for duration, rate, and bioav (except when SS). Shows that fitting lags by direct AD isn't possible in our setup (we can work around it, it's not easy, leaving for later).

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
The weird thing is what to do with time-based is that, what is time? So the lag is calculated at `pre(ev.time)`, and then the other DCPs are at `pre(ev.time + lag)`, since that's the actual time of the dosing, if `lag` exists in there. It's a little odd but it's the most correct model I could think of.

**Comment by ChrisRackauckas** [comment]
So it looks like the complication in the DCP fitting should only exist when there are steady states, except for lags.

**Comment by ChrisRackauckas** [comment]
I'm only testing the AD here, so someone else should do a follow-up PR to add tests for the fitting. But if the AD works that should be fairly straightforward.

**Comment by ChrisRackauckas** [comment]
AD cannot get derivatives of lags. It's the same problem as https://discourse.julialang.org/t/differentiating-through-a-jump-problem/31496/11?u=chrisrackauckas . Because the discontinuity is modeled discretely, there is no connection between the dose time and the `u` which gives a direct effect from the duals. This could be handled more manually in our case, but that's a whole ballgame I'm going to have to leave for later.

**Comment by ChrisRackauckas** [comment]
Issues to open after this PR:

- [ ] Tests fitting rate and duration. This only shows AD should always work, which tells us fitting should work, but doesn't directly test fitting.
- [ ] Tests fitting bioav. Currently will fail on steady state dosing.
- [ ] Issue on fitting with ContinuousCallbacks. Need to handle the t numtype in that case.
- [ ] Issue on fitting bioav with steady state dosing
- [ ] Issue on fitting lags

We can close the old DCP fitting issue though since its examples should all be handled.

**Comment by ChrisRackauckas** [comment]
I ended up handling the ContinuousCallbacks AD issue, so now it just needs tests, so that bullet was changed.

**Comment by pkofod** [comment]
This looks good. Conceptually, lags is a bit strange in my view, but changes look good.

**Comment by ChrisRackauckas** [comment]
Yeah, I'm not sure time-varying lags actually come up... but if they do, at least it has a sensible interpretation.

**Pull request merged**
