### PR TITLE
Use map instead of broadcast in read_pumas

### PR DESCRIPTION
**Pull request by asinghvi17**
Workaround for JuliaData/DataFrames.jl#1907

cc @pkofod @ChrisRackauckas - will this patch produce the correct behaviour?

### CODE REVIEW

**Comment by asinghvi17** [comment]
Doesn't look like it, tested with an example from the tutorials.

**Comment by asinghvi17** [comment]
Gitlab isn't running - is the CI active?

**Comment by ChrisRackauckas** [comment]
It should be. Give it a sec.

**Comment by pkofod** [comment]
does this fix the error in #624 ?

**Comment by asinghvi17** [comment]
Think so :) read_pumas works with latest DF at least

**Comment by andreasnoack** [comment]
It looks like this isn't right. The NLME tests are completely off

**Comment by ChrisRackauckas** [comment]
I don't immediately see why Refing those last ones wouldn't work, but if the tests fail then it needs to get looked into further.

**Comment by andreasnoack** [comment]
I think the implementation here assumes broadcasting behavior but `map` doesn't broadcast. Maybe simpler to use a comprehension.

**Comment by asinghvi17** [comment]
Will make the change.  Has Gitlab still not triggered?

**Comment by andreasnoack** [comment]
GitLab did run the tests. That was how I realized that there was a problem with the implementation. For some reason, the webhook hasn't gone through which is why the test status is still pending here. You can (hopefully) see the test results here https://gitlab.com/PumasAI/Pumas-jl/pipelines/75347608

**Comment by asinghvi17** [comment]
Superseded by #628, thanks @andreasnoack!

**Pull request closed without merging**
