### PR TITLE
fixedcoef -> constantcoef

### PR DESCRIPTION
**Pull request by pkofod**
Fixedcoef might have been a bad choice of name in a population model context as pointed out by @andreasnoack . Constant is consistent with `ConstantDomain` and `ConstantTransformation`.

### CODE REVIEW

**Comment by pkofod** [comment]
@vjd mentioned `fix` as an alternative in #660 - happy to discuss here

**Comment by pkofod** [comment]
So apparently it's called `ConstDomain` but `ConstantTransform`:) so the question is whether we call it `constcoef` (`const_coef)` or `constantcoef` (`constant_coef`)...

**Comment by vjd** [comment]
`contstantcoef` is fine too. All other software use either `fix` or `freeze`, so thought we may want to think in those lines

**Comment by pkofod** [comment]
I think `fix` could be okay with me as well.

**Comment by vjd** [comment]
being verbose/explicit help, so, if we go with your proposals, then I would suggest `constantcoef` with (`constant`) spelled out fully

**Comment by vjd** [comment]
between `constantcoef` and `fix`, I vote for with `fix`. 

The example tests don't provide this information, but can we also `fix` `omega`'s?

**Comment by pkofod** [comment]
> The example tests don't provide this information, but can we also `fix` `omega`'s?

Yes, I can add a test, but of course you have to specify what the "omegas" are (since they could be called anything)

**Comment by andreasnoack** [comment]
My gut feeling is that `fix` is sufficiently distinct from `fixed` to avoid confusing so I'm fine with that although I slightly prefer `constant`.

We should make `Domain` and `Transform` consistent with respect to `Const` and `Constant`. I prefer `Constant` but `ConstDomain` is user facing so it would be more breaking to change `ConstDomain`. It can be deprecated, though, so we would avoid hard fails and the deprecations could be completed by ACoP.

**Comment by vjd** [comment]
sounds good! I am going to merge this for now.

**Pull request merged**
