### PR TITLE
Introduce coef from StatsBase (to replace dot param)

### PR DESCRIPTION
**Pull request by pkofod**
Allows you to dot over an array of results for example
```julia
julia> coef.(fit(model, data, param, Pumas.TwoStage()))
1000-element Array{NamedTuple{(:tvcl, :tvv, :pmoncl, :σ_prop),NTuple{4,Float64}},1}:
 (tvcl = 3.956812926185684, tvv = 72.53618471789329, pmoncl = -0.7030230695000282, σ_prop = 0.0406461355236994)  
 (tvcl = 3.993562978797279, tvv = 74.1751412711836, pmoncl = -0.7, σ_prop = 0.03793161584807546)                 
 (tvcl = 4.050950696977464, tvv = 67.366322846916, pmoncl = -0.7, σ_prop = 0.04050828216599603)                  
 (tvcl = 4.124829610648733, tvv = 74.99894708075536, pmoncl = -0.7, σ_prop = 0.048125999125320756)               
 (tvcl = 4.003060923780999, tvv = 66.53927104040619, pmoncl = -0.6997836299633489, σ_prop = 0.038097925132883806)
 (tvcl = 4.050476182304833, tvv = 74.02456665194552, pmoncl = -0.7, σ_prop = 0.038018325566677155)               
 (tvcl = 4.165727259812076, tvv = 69.73007745151695, pmoncl = -0.6884121346802627, σ_prop = 0.05597094605898037) 
 (tvcl = 4.003211810181148, tvv = 66.95193667001277, pmoncl = -0.6997733295064417, σ_prop = 0.037789068318543166)
 (tvcl = 3.9461693537495717, tvv = 73.34969274997715, pmoncl = -0.7037975112641968, σ_prop = 0.04037498736498542)
 (tvcl = 4.008896920072012, tvv = 70.26989779556857, pmoncl = -0.6994133881213231, σ_prop = 0.04718743265059295) 
 ⋮                                                                                                               
 (tvcl = 3.8673903230951154, tvv = 63.00371487597103, pmoncl = -0.7, σ_prop = 0.031914284691222226)              
 (tvcl = 4.102670447066315, tvv = 74.32896475227959, pmoncl = -0.7, σ_prop = 0.0431962285891008)                 
 (tvcl = 3.9531210227071667, tvv = 71.88356109367646, pmoncl = -0.7032920361250226, σ_prop = 0.03663897388989417)
 (tvcl = 4.010190797701901, tvv = 68.05868028598236, pmoncl = -0.6992870491898036, σ_prop = 0.03366885615354695) 
 (tvcl = 3.9880805839149436, tvv = 65.13591048285663, pmoncl = -0.7, σ_prop = 0.029866071317551594)              
 (tvcl = 3.897019786003249, tvv = 73.36302715002768, pmoncl = -0.70727707237861, σ_prop = 0.037090895479859186)  
 (tvcl = 3.918953342761302, tvv = 72.46881906863214, pmoncl = -0.7056858476727979, σ_prop = 0.03654257872832555) 
 (tvcl = 4.132589240325271, tvv = 68.89698623351538, pmoncl = -0.6907651894724367, σ_prop = 0.048002221671165676)
 (tvcl = 3.956885314040246, tvv = 73.25686636001055, pmoncl = -0.7030453904123943, σ_prop = 0.0399222663303781)  

 ```

### CODE REVIEW

**Comment by pkofod** [comment]
So, I don't think we should change anything on the `PumasModel` side of things, because `coef` is specifically a statistics API. I also didn't remove the `:param` `getproperty` overload, because that is probably used all over, but we should make a switch at some point.

**Comment by pkofod** [comment]
I'm going all rambo on this one and merging. Based on communication irl and slack this is good to go. It's tested, makes sense to extend the statsbase compatibility, and I kept the `getproperty` so tutorials etc isn't messed with.

**Comment by andreasnoack** [comment]
I think we should deprecate the `getproperty` version. Maybe we should switch all tutorials and docs first and then deprecate.

**Comment by vjd** [comment]
so, just to understand, we should take out the `res.param` version of showing outputs?

**Comment by andreasnoack** [comment]
Yes. All places where we used to extract the estimated coefficients with `res.param` should now use `coef(res)`.

**Comment by vjd** [comment]
We can change

**Comment by Nosferican** [comment]
If there are any accessors that need to be extended in the `StatisticalModel`/`RegressionModel` API let me know and I can work on it at the StatsBase repo.

**Pull request merged**
